"""empty message

Revision ID: 726ef4cd44fb
Revises: db2e99b8c42c
Create Date: 2021-04-14 15:56:59.727885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726ef4cd44fb'
down_revision = 'db2e99b8c42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'teste')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('teste', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
