"""criando as tabelas

Revision ID: 9072784c6987
Revises: 
Create Date: 2021-04-21 18:12:49.361066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9072784c6987'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.String(), nullable=False))
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('orders', 'adress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('adress', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('orders', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###
