"""add tables

Revision ID: 931529ea0735
Revises: f028c83f00b9
Create Date: 2021-04-19 12:22:27.371105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931529ea0735'
down_revision = 'f028c83f00b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
